package bilingual.entity.enums;

public enum QuestionType {
    SELECT_MAIN_IDEA,
    SELECT_THE_BEST_TITLE,
    RECORD_SAYING,
    DESCRIBE_IMAGE,
    SELECT_REAL_ENGLISH_WORD,
    LISTEN_AND_SELECT_WORD,
    TYPE_WHAT_YOU_HEAR,
    RESPOND_IN_AT_LEAST_N_WORDS,
    HIGHLIGHTS_THE_ANSWER,

}

